---
 - hosts: mywebservers
   become: yes
   tasks:
    - name: i want to install git 
      apt:
       name: git 
       state: present
    # - name: i want to install tree
    #   apt:
    #    name: tree
    #    state: present  
    - name: apt update && apt install tree -y
      apt:
       update_cache: yes
       name: tree
       state: present    
       