---
 - hosts: mywebservers
   become: yes
   tasks:
    - name: i want to install git 
      apt:
       name: git 
       state: present
      when: ansible_os_family =="Debian"
  
    - name: apt update && apt install tree -y
      apt:
       update_cache: yes
       name: tree
       state: present    
       